# Generated by Django 6.0 on 2026-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('runtime', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='movies')),
            ],
        ),
    ]
